addons:
  apt:
    packages:
      - xvfb
language: node_js
node_js:
  - "9.3.0"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - "npm install"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - "npm run test"